local_backend: true

backend:
  name: git-gateway
  branch: main # Change to your default branch

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featured_image", widget: "image", required: false }
      - { label: "Categories", name: "categories", widget: "list", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Description (short)", name: "description", widget: "text", required: false }
      - { label: "SEO Title", name: "seo_title", widget: "string", required: false }
      - { label: "Meta description", name: "meta_description", widget: "text", required: false }
      - { label: "Canonical URL", name: "canonical", widget: "string", required: false }
      - label: "SEO Keywords"
        name: "keywords"
        widget: "list"
        field: { label: "Keyword", name: "keyword", widget: "string" }
        required: false
      - { label: "Body", name: "body", widget: "markdown" }
